
Project  "pxnGoCommon-Includes-Updater"
	Path  "includes-updater"

Project  "pxnGoCommon-Utils"
	Path  "utils"

Project  "pxnGoCommon-Service"
	Path  "service"

Project  "pxnGoCommon-Net"
	Path  "net"

Project  "pxnGoCommon-RPC"
	Path  "rpc"

Project  "pxnGoCommon-SQL"
	Path  "sql"

Project  "pxnGoCommon-Fonts"
	Path  "fonts"

Project  "pxnGoCommon-Badge"
	Path  "badge"


Project  "pxnGoCommon"
	AddIgnore  "includes-updater/includes-updater"
